version: '3.5'

services:

  web_server:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    env_file: docker/nginx.conf
    ports:
      - "80:80"

    networks:
      - web_nw
    depends_on:
      - app

  app:
    container_name: flask
    build:
          context: .
          dockerfile: docker/flask/Dockerfile
    env_file: docker/database.conf
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    env_file: docker/database.conf
    ports:
      - 5432:5432
    networks:
      - db-nw
    volumes:
      - "dbdata:/var/lib/postgresql/data"

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  dbdata: